### ISSUE TITLE
purpose of plugin

### ISSUE THREAD

**Issue by bnomei** [omz13/kirby3-suncyclepages#1]
just close this issue if you rhinks its not needed to respond. i am just curious. this plugin is big but i do not understand its benefits fully. 

why not solve this using core concepts and making pages drafts/not drafts based on date and a cron job?

imho adding embargo checks to all calls of collections etc seems to be tricky to pull of perfect.

**Comment by omz13** [comment]
I'll add a use case to the README to better explain; embargo and sunsetting of content is an established methodology for those who are working in some domains.

As for using a cron job and using that to change the status: that is an alternative method to achieve something similar, but it has some disadvantages: you have to establish a cron job and associated script(s) to do the status changes; you now have to somehow monitor cron to ensure that the job is run (and you would be surprised at how often when something goes wrong with a cron job nobody notices because everybody assumes they always work); your temporal granularity for removing an embargo or withdrawing a page is now set to that of the cron job.
